"""Update tables

Revision ID: d8297e7f6964
Revises: 0c24f114ee2f
Create Date: 2026-04-05 11:20:06.365249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8297e7f6964'
down_revision: Union[str, Sequence[str], None] = '0c24f114ee2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('lessons_module_id_fkey'), 'lessons', type_='foreignkey')
    op.create_foreign_key(None, 'lessons', 'modules', ['module_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('tasks_lesson_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_lesson_id_fkey'), 'tasks', 'lessons', ['lesson_id'], ['id'])
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.create_foreign_key(op.f('lessons_module_id_fkey'), 'lessons', 'modules', ['module_id'], ['id'])
    # ### end Alembic commands ###
