"""Create stars table

Revision ID: 966b6af55f7f
Revises: d8297e7f6964
Create Date: 2026-04-09 10:46:01.949476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '966b6af55f7f'
down_revision: Union[str, Sequence[str], None] = 'd8297e7f6964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('star_transactions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('DAILY_REWARD', 'PURCHASE', 'SPEND', name='transactiontype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('stars', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('last_daily_reward', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_daily_reward')
    op.drop_column('users', 'stars')
    op.drop_table('star_transactions')
    # ### end Alembic commands ###
