"""Update task table

Revision ID: f0cfba884c56
Revises: e7e9e63a7160
Create Date: 2026-04-13 11:02:11.500522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0cfba884c56'
down_revision: Union[str, Sequence[str], None] = 'e7e9e63a7160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('options', sa.JSON(), nullable=True))
    op.add_column('tasks', sa.Column('correct_answers', sa.JSON(), nullable=True))
    op.add_column('tasks', sa.Column('multiple', sa.Boolean(), nullable=False))
    op.alter_column('tasks', 'answer',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'answer',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('tasks', 'multiple')
    op.drop_column('tasks', 'correct_answers')
    op.drop_column('tasks', 'options')
    # ### end Alembic commands ###
