"""Add input/output to problems

Revision ID: ac220e3e24d1
Revises: c83d57fca224
Create Date: 2026-04-20 12:02:41.537743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac220e3e24d1'
down_revision: Union[str, Sequence[str], None] = 'c83d57fca224'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('input_data', sa.Text(), nullable=False))
    op.add_column('problems', sa.Column('expected_output', sa.Text(), nullable=False))
    op.drop_column('problems', 'solution')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('solution', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('problems', 'expected_output')
    op.drop_column('problems', 'input_data')
    # ### end Alembic commands ###
