"""add test cases on problems

Revision ID: 09397c933802
Revises: ab8799bbda47
Create Date: 2026-04-22 11:08:51.904112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09397c933802'
down_revision: Union[str, Sequence[str], None] = 'ab8799bbda47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('test_cases', sa.JSON(), nullable=False))
    op.drop_column('problems', 'expected_output')
    op.drop_column('problems', 'input_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('input_data', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('problems', sa.Column('expected_output', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('problems', 'test_cases')
    # ### end Alembic commands ###
