"""add test cases on tasks

Revision ID: ab8799bbda47
Revises: ac220e3e24d1
Create Date: 2026-04-22 10:55:48.692761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab8799bbda47'
down_revision: Union[str, Sequence[str], None] = 'ac220e3e24d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('test_cases', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'test_cases')
    # ### end Alembic commands ###
